## ============================================================================
## File name   : config.toml
## Description : Hugo site configuration file for sbml.org
## Author(s)   : Michael Hucka <mhucka@caltech.edu>
## Organization: California Institute of Technology
## Date created: 2019-03-19
##
## Notes about this file
## ~~~~~~~~~~~~~~~~~~~~~
##
## This config.toml is at the top level of the site.  I moved config.toml to
## the top level after getting rid of the Academic theme's cofnig/_default
## directory where it was originally located along with two other config
## files (params.toml, menus.toml).  I found the differences between the
## variables set in params.toml and those in config.toml to be completely
## incomprehensible -- they *all* seemed like site configuration variables,
## as far as I could understand them -- so I merged the contents of
## params.toml and config.toml into this config.toml.  Further, since our
## menus.toml ended up quite small, I put its contents in here (config.toml)
## as well.  Section headings in this file try to help nagivation and
## understanding.
##
## The config/_default directory originally used by the Academic theme
## example site is not used for this site (there was no point after the
## changes above), which IMHO has the advantage of further simplifying things
## and reducing the number of things that future maintainers need to wade
## through to understand the site.
##
## ============================================================================


# General configuration variables for Hugo and the Hugo Academic theme. 
# .............................................................................

# Title of the site
title = "SBML"

# The URL of the site.  Needs to end with a '/' -- e.g. `https://example.com/`
baseurl = "/"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Name of Academic theme folder in `themes/`.
# The SBML site overrides some of the configuration and features of this.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = true

# Enable Emoji emoticons support for page content.
enableEmoji = true

# Files to be ignored by Hugo.
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.#"]

paginate = 10  # Number of items per page in paginated lists.

footnotereturnlinkcontents = "<sup>^</sup>"

[outputs]
  home = [ "HTML", "CSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab.
  angledQuotes = false
  latexDashes = true
  extensions = ["backslashLineBreak"]

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"
  

# Theme options.
# .............................................................................
# These are variables in the Academic theme for Hugo, and some additional
# ones for our SBML.org customizations.

[params]
  color_theme = "sbml"
  font = "sbml"
  
  # Enable users to switch between day and night mode?
  day_night = true
  
  # Description for social sharing and search engines. If undefined,
  # superuser role is used in place.
  description = "SBML Home Page"
  
  # Default image for social sharing and search engines. Place image in
  # `static/img/` folder and specify image name here.
  sharing_image = ""
  
  # Twitter username (without @). Used when a vistor shares your site on Twitter.
  twitter = "@sbmlnews"
  
  # Diplay a logo in navigation bar rather than title (optional).  To enable,
  # place an image in `static/img/` and reference its filename below. To
  # disable, set the value to "".
  logo = "sbml-logo.svg"
  
  # Enable global source code highlighting? true/false
  # For supported styles, see https://cdnjs.com/libraries/highlight.js/
  highlight = true
  highlight_languages = ["xml"]
  highlight_style = "solarized-dark"  
  
  # Enable global LaTeX math rendering?
  # If false, you can enable it locally on a per page basis.
  math = true
  
  # Privacy pack
  #   Show a cookie consent message to visitors
  #   Anonymize IP in Google Analytics (if enabled)
  privacy_pack = true
  
  # Date and time format
  # Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "2006-01-02"
  #   Examples: "3:04 pm" or "15:04"
  time_format = "15:04"
  
  # Load CSS and JS plugins
  #   E.g. To load `/assets/css/custom.css`, set `plugins_css = ["custom"]`.
  #   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
  plugins_css = []
  plugins_js  = []

  # Search.
  [search]
    # Search provider:
    #   0: No search engine
    #   1: Academic (built-in)
    #   2: Algolia (https://www.algolia.com)
    engine = 1
  
  ##########################
  # SBML.org features
  ##########################
  
  badge = "Official-sbml-supported-70.jpg"


# Menu (navigation) configuration
# .............................................................................
# Note: the ordering of the section names in the nav bar is *not* set by the
# order of the items in the list below; the weight parameter defines the
# order that the links will appear in.

[menu]
  [[menu.main]]
    name = "News"
    url = "news"
    weight = 1
  
  [[menu.main]]
    name = "Docs"
    url = "documents"
    weight = 2
  
  [[menu.main]]
    name = "Downloads"
    url = "software"
    weight = 3
  
  [[menu.main]]
    name = "Facilities"
    url = "facilities"
    weight = 4
  
  [[menu.main]]
    name = "Showcase"
    url = "community/showcase"
    weight = 5
  
  [[menu.main]]
    name = "Community"
    url = "community"
    weight = 6
  
  [[menu.main]]
    name = "About"
    url = "about"
    weight = 7
